### ISSUE TITLE
projects/project/:id endpoint doesn't seem to work

### ISSUE THREAD

**Issue by mthorsdal** [Weble/RevisoApi#1]
I cannot seem to get the endpoint to get a single project to work. ->project->get() doesn’t seem to work and ->project->projects->get() neither. ->project->find() gives me a collection of projects, but I need the individual one.

**Comment by Skullbock** [comment]
Hi @mthorsdal we just released v1.1.0 that should fix this
Basically, the projects endpoint has a different structure from the rest that required some adjustments.
Be careful that we also moved around some classes, and you may need to update the namespaces if needed

Let me know if it does work

**Comment by mthorsdal** [comment]
Awesome! I’ll check it out soon.

Mads Thorsdal
Travel Industry Entrepreneur

+36 20 459 1770
+45 42 36 73 29

Awesome Adventures Group
Frederiksberggade 2, 5th
DK-1459 Copenhagen

**Comment by Skullbock** [comment]
Hi @mthorsdal is this fixed?

**Comment by mthorsdal** [comment]
Yes, thank you very much!
