### ISSUE TITLE
Class Webleit\RevisoApi\Endpoint\Endpoint not found

### ISSUE THREAD

**Issue by mdds2314** [Weble/RevisoApi#4]
`PHP message: PHP Fatal error:  Uncaught Error: Class 'Webleit\RevisoApi\Endpoint\Endpoint' not found in [redacted]/vendor/webleit/revisoapi/src/Reviso.php:189`

Solved by renaming the "src/EndPoint" directory to "src/Endpoint", with the lowercase P to match the name used by the use directive:
`use Webleit\RevisoApi\Endpoint\Endpoint;`

**Comment by Skullbock** [comment]
Good catch @mdds2314 ! Can you PR the change to the repo?
Thanks
